### ISSUE TITLE
after school function

### ISSUE THREAD

**Issue by eredler** [mpapallo/FinalProject#22]
* homework, study, and facebook don't update time
* after time is 7am (after sleep or you do things to pass time), calls after school one more time before morning

**Comment by mpapallo** [comment]
pretty sure this is fixed now?

**Comment by eredler** [comment]
the times update now but after you sleep it still calls after school again...

**Comment by eredler** [comment]
fixed it. made it so activities are based on time and not the string returned by the previous one and it (mostly) works. the morning function is still a little wonky though.
